In [8]:
import pandas as pd

data = pd.read_csv("E:\Anushka-playground\Gen_AI\Churn_Modelling.csv")
# print(data)
data.head()

<>:3: SyntaxWarning: invalid escape sequence '\A'
<>:3: SyntaxWarning: invalid escape sequence '\A'
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_14948\1835054842.py:3: SyntaxWarning: invalid escape sequence '\A'
  data = pd.read_csv("E:\Anushka-playground\Gen_AI\Churn_Modelling.csv")

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [9]:
import pandas
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [10]:
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis= 1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [11]:
Encoder = LabelEncoder()
data['Gender'] = Encoder.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [12]:
from sklearn.preprocessing import OneHotEncoder
onehot = OneHotEncoder(sparse_output=False)
onehotgeo = onehot.fit_transform(data[['Geography']])
onehotgeo

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [13]:
print(onehot.categories_)

[array(['France', 'Germany', 'Spain'], dtype=object)]

In [14]:
onehot.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [15]:
encode_df = pd.DataFrame(onehotgeo, columns=onehot.get_feature_names_out(['Geography']))
encode_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [16]:
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [17]:
data = pd.concat([data.drop('Geography' , axis = 1),encode_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [18]:
with open('Encoder.pkl', 'wb') as file:
    pickle.dump(Encoder,file)

with open('onehot.pkl', 'wb') as file:
    pickle.dump(onehot,file)

In [19]:
x = data.drop('Exited',axis = 1)
y = data['Exited']

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [20]:
x_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [21]:
with open('scaler.pickle', 'wb') as file:
    pickle.dump(scaler,file)

STARTING WITH IMPLEMENTATION

In [22]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [23]:
(x_train.shape[1],) #form of tupple

(12,)

In [24]:
model = Sequential([
    Dense(64,activation='relu',input_shape = (x_train.shape[1],)), #hidden layer1 with input layer
    Dense(32,activation='relu'), #hidden layer 2
    Dense(1,activation='sigmoid') #output layer
]
)

e:\Anushka-playground\Gen_AI\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [25]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [27]:
import tensorflow
opt = tensorflow.keras.optimizers.Adam(learning_rate=0.001)
loss = tensorflow.keras.losses.BinaryCrossentropy() 
loss

In [28]:
model.compile(optimizer=opt, loss="binary_crossentropy", metrics=['accuracy'])

In [29]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
log_dir = 'logs/fit' + datetime.datetime.now().strftime("%Y%m%d-%H%M.%S")
tensorflow_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [30]:
early_stopping_callback = EarlyStopping(monitor='val_loss',patience=20,restore_best_weights=True)

In [31]:
#training
history = model.fit(
    x_train,y_train,validation_data = (x_test,y_test),epochs = 100,
    callbacks =[ tensorflow_callback, early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.8036 - loss: 0.4500 - val_accuracy: 0.8325 - val_loss: 0.3910
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8422 - loss: 0.3826 - val_accuracy: 0.8530 - val_loss: 0.3561
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8570 - loss: 0.3559 - val_accuracy: 0.8540 - val_loss: 0.3571
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8589 - loss: 0.3473 - val_accuracy: 0.8605 - val_loss: 0.3448
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8597 - loss: 0.3417 - val_accuracy: 0.8600 - val_loss: 0.3470
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8616 - loss: 0.3391 - val_accuracy: 0.8595 - val_loss: 0.3448
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8629 - loss: 0.3356 - val_accuracy: 0.8580 - val_loss: 0.3443
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8629 - loss: 0.3335 - val_accuracy: 0.8565 - val_loss: 0.3418
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8636 - loss: 0.3305 - val_accuracy: 0.8625 - val_loss: 0.3425
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8648 - loss: 0.3288 - val_accuracy: 0.8625 - val_loss: 0.3429
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8637 - loss: 0.3272 - val_accuracy: 0.8595 - val_loss: 0.3408
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8661 - loss: 0.3251 - val_accuracy: 0.8610 - val_loss: 0.3415
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8668 - loss: 0.3227 - val_accuracy: 0.8615 - val_loss: 0.3488
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8668 - loss: 0.3220 - val_accuracy: 0.8635 - val_loss: 0.3413
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8668 - loss: 0.3186 - val_accuracy: 0.8620 - val_loss: 0.3414
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8680 - loss: 0.3172 - val_accuracy: 0.8615 - val_loss: 0.3401
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8680 - loss: 0.3161 - val_accuracy: 0.8630 - val_loss: 0.3387
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8696 - loss: 0.3144 - val_accuracy: 0.8655 - val_loss: 0.3401
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8701 - loss: 0.3122 - val_accuracy: 0.8620 - val_loss: 0.3394
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8714 - loss: 0.3117 - val_accuracy: 0.8645 - val_loss: 0.3362
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8737 - loss: 0.3094 - val_accuracy: 0.8555 - val_loss: 0.3409
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8710 - loss: 0.3090 - val_accuracy: 0.8630 - val_loss: 0.3393
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8712 - loss: 0.3070 - val_accuracy: 0.8560 - val_loss: 0.3463
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8704 - loss: 0.3042 - val_accuracy: 0.8630 - val_loss: 0.3412
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8737 - loss: 0.3030 - val_accuracy: 0.8615 - val_loss: 0.3442
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8741 - loss: 0.3021 - val_accuracy: 0.8640 - val_loss: 0.3435
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8737 - loss: 0.2997 - val_accuracy: 0.8615 - val_loss: 0.3430
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8706 - loss: 0.3007 - val_accuracy: 0.8625 - val_loss: 0.3406
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8755 - loss: 0.2977 - val_accuracy: 0.8630 - val_loss: 0.3443
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8752 - loss: 0.2964 - val_accuracy: 0.8615 - val_loss: 0.3419
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8755 - loss: 0.2962 - val_accuracy: 0.8625 - val_loss: 0.3434
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8765 - loss: 0.2940 - val_accuracy: 0.8560 - val_loss: 0.3502
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8777 - loss: 0.2932 - val_accuracy: 0.8560 - val_loss: 0.3518
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8774 - loss: 0.2919 - val_accuracy: 0.8520 - val_loss: 0.3643
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8790 - loss: 0.2923 - val_accuracy: 0.8565 - val_loss: 0.3477
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8783 - loss: 0.2885 - val_accuracy: 0.8575 - val_loss: 0.3546
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8808 - loss: 0.2886 - val_accuracy: 0.8630 - val_loss: 0.3477
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8791 - loss: 0.2866 - val_accuracy: 0.8575 - val_loss: 0.3489
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8795 - loss: 0.2864 - val_accuracy: 0.8645 - val_loss: 0.3548
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8779 - loss: 0.2865 - val_accuracy: 0.8630 - val_loss: 0.3580

In [32]:
model.save('model.keras')

In [33]:
#load_ext
%reload_ext tensorboard

In [34]:
%tensorboard --logdir logs/fit20260430-1747.13

In [35]:
import tensorflow as tf
import pandas as pd
import numpy as np
from tensorflow.keras.models import load_model

In [36]:
model = load_model('model.keras')

with open('Encoder.pkl', 'rb') as file:
    Encoder = pickle.load(file)

with open('onehot.pkl', 'rb') as file:
    onehot = pickle.load(file)   

with open('scaler.pickle' , 'rb')as file:
    scaler = pickle.load(file)

In [37]:
#example input
input_data = {
    "CreditScore" : 650,
    "Geography": "France",
    "Gender": "Male",
    "Age": 40,
    "Tenure": 3,
    "Balance": 60000,
    "NumOfProducts": 2,
    "HasCrCard": 1,
    "IsActiveMember": 1,
    "EstimatedSalary": 50000
}

In [38]:
import pandas as pd
input_df = pd.DataFrame([input_data])

In [39]:
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,650,France,Male,40,3,60000,2,1,1,50000

In [40]:
geo_encoded = onehot.transform(input_df[['Geography']]) 

geo_encoded_df = pd.DataFrame(geo_encoded,columns=onehot.get_feature_names_out(['Geography']))

In [41]:
input_df['Gender'] = Encoder.transform(input_df['Gender'])

In [42]:
input_df = input_df.drop('Geography', axis=1)

In [43]:
input_df = pd.concat([input_df.reset_index(drop=True),geo_encoded_df.reset_index(drop=True)],axis=1)

In [ ]:
input_scaled = scaler.transform(input_df)

In [45]:
input_scaled

array([[-0.01709861,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [46]:
prediction = model.predict(input_scaled)

print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 673ms/step
[[0.03604251]]

In [ ]:
#App start